name: Publishing new assets
on:
  push:
    branches:
      - master
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: WordPress.org plugin asset/readme update
        uses: ./.github/actions/upload-assets
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: moloni-es